const ISLOGIN = 'ISLOGIN'
const ISVENDOR = 'ISVENDOR'
const ISUSER = 'ISUSER'
const NAME = 'NAME'
const EMAIL = 'EMAIL'
const PASSWORD = 'PASSWORD'
const CONFIRMPASSWORD = 'CONFIRMPASSWORD'
const PHONE = 'PHONE'
const SURNAME = 'SURNAME'
const PICTURE = 'PICTURE'
const ISAUDIOBOOK = 'ISAUDIOBOOK'
const ISPAPPERBOOK = 'ISPAPPERBOOK'
const ISELECTROBOOK = 'ISELECTROBOOK'

export { 
    ISLOGIN,
    ISUSER,
    ISVENDOR,
    NAME,
    EMAIL,
    PASSWORD,
    CONFIRMPASSWORD,
    PHONE,
    SURNAME,
    PICTURE,
    ISAUDIOBOOK,
    ISPAPPERBOOK,
    ISELECTROBOOK
}
